---
- hosts: all
  sudo: yes
  vars:
    java_version: 1.8.0
    git_version: 2.4.2
  tasks:
    - name: Add a new user
      user: name=t-hara

    - name: Install dependencies packages
      yum: name={{item}} state=latest
      with_items:
        - gcc
        - gcc-c++
        - java-{{java_version}}
        - curl-devel
        - expat-devel
        - gettext-devel
        - openssl-devel
        - zlib-devel
        - perl-ExtUtils-MakeMaker
        - libselinux-python

    - name: Check git source file existence
      command: ls /tmp/git-{{git_version}}.tar.gz
      ignore_errors: True
      register: git_source_exists

    - name: Download git source file
      copy: src=./files/packages/git-{{git_version}}.tar.gz dest=/tmp/git-{{git_version}}.tar.gz
      when: git_source_exists|failed

    - name: Unarchive git.tar.gz
      command: chdir=/tmp/ tar zxf git-{{git_version}}.tar.gz
      when: git_source_exists|failed

    - name: Check git is installed
      command: which git
      ignore_errors: True
      register: git_is_installed
      sudo: no

    - name: Configure git source
      command: chdir=/tmp/git-{{git_version}} ./configure --prefix=/usr/local
      when: git_is_installed|failed

    - name: Make git
      command: chdir=/tmp/git-{{git_version}} make prefix=/usr/local all
      when: git_is_installed

    - name: Install git
      command: chdir=/tmp/git-{{git_version}} make prefix=/usr/local install

#================================================
# Install td-agent2
#================================================
- hosts:
    - fluentd
    - es
    - nk
  sudo: yes
  tasks:
    - name: Download td-agent2 installer
      get_url: url=https://td-toolbelt.herokuapp.com/sh/install-redhat-td-agent2.sh dest=/tmp/install-redhat-td-agent2.sh
    - name: Change mode of td-agent2 installer
      file: path=/tmp/install-redhat-td-agent2.sh mode="u=rwx,g=rw,o=rw"
    - name: Execute td-agent2 installer
      shell: /tmp/install-redhat-td-agent2.sh

#================================================
# Copy fluentd config files
#================================================
- hosts: fluentd
  sudo: yes
  tasks:
    - name: Copy config file
      copy: src=./files/fluentd-aggregator.conf dest=/etc/td-agent/td-agent.conf

- hosts: es
  sudo: yes
  tasks:
    - name: Copy config file
      copy: src=./files/fluentd-es.conf dest=/etc/td-agent/td-agent.conf

- hosts: nk
  sudo: yes
  tasks:
    - name: Copy config file
      copy: src=./files/fluentd-nk.conf dest=/etc/td-agent/td-agent.conf

#================================================
# Install Elasticsearch
# ref: http://qiita.com/dayflower/items/21c64a6f5da155a5ade3
#================================================
- hosts: es
  sudo: yes
  vars:
    es_version: 1.5.2
    kibana_version: 4.0.2
  tasks:
    - name: Copy rpm file
      copy: src=./files/packages/elasticsearch-{{es_version}}.noarch.rpm dest=/tmp/elasticsearch-{{es_version}}.noarch.rpm
    - name: Install Elasticsearch
      yum: name=/tmp/elasticsearch-{{es_version}}.noarch.rpm
    - name: Download kibana
      copy: src=./files/packages/kibana-{{kibana_version}}-linux-x64.tar.gz dest=/tmp/kibana-{{kibana_version}}-linux-x64.tar.gz
    - name: Unarchive kibana.tar.gz
      command: tar zxf /tmp/kibana-{{kibana_version}}-linux-x64.tar.gz
    - name: Move kibana
      command: mv /home/vagrant/kibana-{{kibana_version}}-linux-x64 /usr/local/bin/
    - name: Install fluent-plugin-elasticsearch
      command: td-agent-gem install fluent-plugin-elasticsearch

#================================================
# Install Norikra
#================================================
- hosts: nk
  user: vagrant
  vars:
    ruby_version: 2.2.2
    jruby_version: 1.7.20
  tasks:
    # Install rbenv
    - name: Clone rbenv.git
      git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
    - name: Clone ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
    - name: edit .bash_profile 1
      shell: echo 'export PATH=$HOME/.rbenv/bin:$PATH' >> ~/.bash_profile
    - name: edit .bash_profile 2
      shell: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    - name: apply .bash_profile
      shell: source ~/.bash_profile

    # Install ruby and jruby
    - name: install ruby
      command: $HOME/.rbenv/bin/rbenv install {{ruby_version}}
    - name: install jruby
      command: $HOME/.rbenv/bin/rbenv install jruby-{{jruby_version}}

    # Install norikra
    - name: make workspace for norikra
      file: path=~/norikra state=directory owner=vagrant group=vagrant mode=0755
    - name: copy Gemfile
      copy: src=./files/Gemfile dest=~/norikra/Gemfile
    - name: set local ruby version
      command: chdir=~/norikra $HOME/.rbenv/bin/rbenv local jruby-{{jruby_version}}
    - name: install bundler
      command: chdir=~/norikra $HOME/.rbenv/versions/jruby-{{jruby_version}}/bin/gem install bundler
    - name: install norikra
      command: chdir=~/norikra $HOME/.rbenv/versions/jruby-{{jruby_version}}/bin/bundle install

    # Install fluent-plugins
    - name: Install fluent-plugin-norikra
      command: td-agent-gem install fluent-plugin-norikra
      sudo: yes
    - name: Install fluent-plugin-elasticsearch
      command: td-agent-gem install fluent-plugin-elasticsearch
      sudo: yes

#================================================
# Install Gitbucket
#================================================
- hosts: git
  sudo: yes
  vars:
    tomcat_version: 8.0.23
    gb_version: 3.2
  tasks:
    - name: Add User for tomcat
      user: name=tomcat shell=/sbin/nologin
    - name: Copy tomcat
      copy: src=./files/packages/apache-tomcat-{{tomcat_version}}.tar.gz dest=/tmp/apache-tomcat-{{tomcat_version}}.tar.gz
    - name: Unarchive tomcat
      shell: chdir=/tmp/ tar zxf apache-tomcat-{{tomcat_version}}.tar.gz
    - name: Move tomcat
      shell: mv /tmp/apache-tomcat-{{tomcat_version}} /usr/local/tomcat

    - name: Copy Gitbucket
      copy: src=./files/packages/gitbucket.war dest=/usr/local/tomcat/webapps/gitbucket.war
    - name: Change owner tomcat directory
      file: path=/usr/local/tomcat owner=tomcat group=tomcat recurse=yes
